parameters:
- name: environment
  type: object

stages:
- stage: ${{ parameters.environment.name }}
  dependsOn: ${{ parameters.environment.dependsOn }}
  variables:
    - template: ../variables/${{parameters.environment.name}}.yml

  jobs:
  - deployment: DeployToEnvironment
    displayName: Deploy to ${{parameters.environment.name}}
    environment: ${{parameters.environment.name}}-pipelines-demo
    strategy:
        runOnce:
          deploy:
            steps:
            - task: DownloadPipelineArtifact@2
              displayName: 'Download artifact'
              inputs:
                artifactName: 'drop'
                targetPath: $(Pipeline.Workspace)

            - task: AzureWebApp@1
              displayName: 'Deploy to Azure Web App'
              inputs:
                azureSubscription: '$(subscription)'
                appName: '$(appServiceName)'
                package: '$(Pipeline.Workspace)/drop)/**/*.zip'